
#ifndef NEO_COLOR_H
#define NEO_COLOR_H

typedef enum NEO_Color{ 
	NEO_COLOR_NEGRO			= 0,
	NEO_COLOR_AZUL    		= 1,
	NEO_COLOR_VERDE			= 2,
	NEO_COLOR_CYAN			= 3,
	NEO_COLOR_ROJO			= 4,
	NEO_COLOR_MORADO	                = 5,
	NEO_COLOR_CAFE			= 6,
	NEO_COLOR_GRISCLARO		= 7,
	NEO_COLOR_GRISOSCURO		= 8,
	NEO_COLOR_AZULCLARO		= 9,
	NEO_COLOR_VERDECLARO	        = 10,
	NEO_COLOR_CYANCLARO		= 11,
	NEO_COLOR_ROJOCLARO		= 12,
	NEO_COLOR_MORADOCLARO	        = 13,
	NEO_COLOR_CAFECLARO	        = 14,
	NEO_COLOR_BLANCO			= 15

} NEO_Color;
#endif
